server:
  port: 8081

spring:
  application:
    name: order-service

demo:
  payment:
    base-url: http://127.0.0.1:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      service: order-service

logging:
  level:
    root: INFO
    com.aiops.demo.order: DEBUG
