server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:file:./data/payment-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      service: payment-service

logging:
  level:
    root: INFO
    com.aiops.demo.payment: DEBUG
